name: worker_app
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.1
  show_up_animation: ^2.0.0
  material_design_icons_flutter: ^5.0.6595
  circular_profile_avatar: ^2.0.0
  audio_wave: ^0.1.2
  table_calendar: ^3.0.5
  intl: ^0.17.0
  buttons_tabbar: ^1.3.4
  intl_phone_number_input: ^0.7.0+2
  async: ^2.8.2
  dotted_border: ^2.0.0+2
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.6
  http: ^0.13.3
  video_player: 2.3.0

  image_picker: ^0.8.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
